package com.storagesweep.app.ui

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.storagesweep.app.appmanager.AppCacheEntry
import com.storagesweep.app.appmanager.OrphanType
import com.storagesweep.app.shizuku.ShizukuState
import com.storagesweep.app.util.toHumanBytes

@Composable
fun CacheManagerScreen(viewModel: MainViewModel, onBack: () -> Unit) {
    val state by viewModel.cacheState.collectAsStateWithLifecycle()
    val shizuku by viewModel.shizukuState.collectAsStateWithLifecycle()
    var pending by remember { mutableStateOf<AppCacheEntry?>(null) }
    LaunchedEffect(Unit) { viewModel.scanAppCaches() }

    Scaffold { padding ->
        Column(Modifier.fillMaxSize().padding(padding).padding(16.dp)) {
            Header("App Cache Manager", onBack)
            Spacer(Modifier.height(8.dp))
            Text("Only Android-reported app cache is listed. Cache clearing requires authorized Shizuku on this build.", style = MaterialTheme.typography.bodySmall)
            Spacer(Modifier.height(12.dp))
            when (val s = state) {
                CacheUiState.Idle, CacheUiState.Loading -> CircularProgressIndicator()
                is CacheUiState.Ready -> {
                    val total = s.entries.sumOf { it.cacheBytes }
                    Text("Detected cache: ${total.toHumanBytes()}", style = MaterialTheme.typography.titleMedium)
                    Spacer(Modifier.height(8.dp))
                    if (s.entries.isEmpty()) Text("No non-zero app cache was reported.")
                    LazyColumn(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        items(s.entries, key = { it.app.packageName }) { entry ->
                            Card(Modifier.fillMaxWidth().clickable { pending = entry }) {
                                Column(Modifier.padding(14.dp)) {
                                    Text(entry.app.label, style = MaterialTheme.typography.titleMedium)
                                    Text(entry.app.packageName, style = MaterialTheme.typography.bodySmall)
                                    Text(entry.cacheBytes.toHumanBytes(), style = MaterialTheme.typography.titleSmall)
                                    Text(if (shizuku == ShizukuState.RUNNING_AUTHORIZED) "Tap to clear cache" else "Tap for system app settings", style = MaterialTheme.typography.labelSmall)
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    pending?.let { entry ->
        AlertDialog(
            onDismissRequest = { pending = null },
            title = { Text(entry.app.label) },
            text = { Text("Reported cache: ${entry.cacheBytes.toHumanBytes()}\n\nCache can normally be regenerated by the app.") },
            confirmButton = {
                if (shizuku == ShizukuState.RUNNING_AUTHORIZED) {
                    Button(onClick = { viewModel.clearAppCache(entry.app.packageName); pending = null }) { Text("Clear cache") }
                }
            },
            dismissButton = { OutlinedButton(onClick = { pending = null }) { Text("Close") } }
        )
    }
}

@Composable
fun OrphanManagerScreen(viewModel: MainViewModel, onBack: () -> Unit) {
    val state by viewModel.orphanState.collectAsStateWithLifecycle()
    var pending by remember { mutableStateOf<com.storagesweep.app.appmanager.OrphanedDirectory?>(null) }
    LaunchedEffect(Unit) { viewModel.scanOrphanedDirectories() }

    Scaffold { padding ->
        Column(Modifier.fillMaxSize().padding(padding).padding(16.dp)) {
            Header("Orphaned App Data", onBack)
            Spacer(Modifier.height(8.dp))
            Text("Checks Android/data and Android/obb for package-shaped directories whose packages are no longer installed.", style = MaterialTheme.typography.bodySmall)
            Spacer(Modifier.height(12.dp))
            when (val s = state) {
                OrphanUiState.Idle, OrphanUiState.Loading -> CircularProgressIndicator()
                is OrphanUiState.Ready -> {
                    Text("Found ${s.items.size} orphaned directories", style = MaterialTheme.typography.titleMedium)
                    Spacer(Modifier.height(8.dp))
                    if (s.items.isEmpty()) Text("No orphaned app data or OBB directories were found.")
                    LazyColumn(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        items(s.items, key = { it.path }) { item ->
                            Card(Modifier.fillMaxWidth().clickable { pending = item }) {
                                Column(Modifier.padding(14.dp)) {
                                    Text(item.packageName, style = MaterialTheme.typography.titleMedium)
                                    Text(if (item.type == OrphanType.OBB) "OBB / game data" else "App data", style = MaterialTheme.typography.labelMedium)
                                    Text(item.sizeBytes.toHumanBytes(), style = MaterialTheme.typography.titleSmall)
                                    Text(item.path, style = MaterialTheme.typography.bodySmall)
                                    Text("Review before deleting", style = MaterialTheme.typography.labelSmall)
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    pending?.let { item ->
        AlertDialog(
            onDismissRequest = { pending = null },
            title = { Text("Delete orphaned data?") },
            text = { Text("${item.path}\n\n${item.sizeBytes.toHumanBytes()}\n\n${item.reason}\n\nThis directory belongs to a package that is not currently installed. Make sure another user/profile or manual installation is not using it.") },
            confirmButton = {
                Button(onClick = { viewModel.deleteOrphan(item.path); pending = null }) { Text("Delete") }
            },
            dismissButton = { OutlinedButton(onClick = { pending = null }) { Text("Cancel") } }
        )
    }
}

@Composable
private fun Header(title: String, onBack: () -> Unit) {
    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
        Text(title, style = MaterialTheme.typography.headlineMedium)
        OutlinedButton(onClick = onBack) { Text("Back") }
    }
}
